@HOST=http://localhost:8000

###
POST {{HOST}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "gremlich@duck.com",
    "password": "password"
}

###
DELETE {{HOST}}/api/auth/register/delete?certain=yes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE3NzE2NDUsImV4cCI6MTcxNDE5MDg0NSwiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZSI6WyJ1c2VyIl19.gd5h0cT2wAWxnpn8X6xFovBShBN5uF62n4E4V1FmQ6O0Fk7sCOOHxk4EjRFCqwC_iSiQytgEL_0sbvy1HbiHTA

###
GET {{HOST}}/api/token/oneTime/issue HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE3NjkyMTcsImV4cCI6MTcxNDE4ODQxNywiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZSI6WyJ1c2VyIl19.pYk1h9cPHfYlPA8nigWZ7M100CUzw2vzP2VP5H-0oB2pKx9DmYTXXGMr8BH6GsoMVKortiujCBXmkf1EnnZ0gA

###
POST {{HOST}}/api/token/oneTime/verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE3NjkyMTcsImV4cCI6MTcxNDE4ODQxNywiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZSI6WyJ1c2VyIl19.pYk1h9cPHfYlPA8nigWZ7M100CUzw2vzP2VP5H-0oB2pKx9DmYTXXGMr8BH6GsoMVKortiujCBXmkf1EnnZ0gA

{
    "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzY2FtLWhvdW5kLXNlcnZpY2UiLCJleHAiOjE3MTQxODk2MjksImlhdCI6MTcxMTc3MDQyOSwidXNlZCI6ZmFsc2V9.dR_39nBIpewCymaBBawGRcY7kZ1d4XLjZTl-JFcoEyDi0dWlbOSjz8sOt97kjnlaCo5o3QPWiC53dJQo8UZnKA"
}