@HOST=http://localhost:8000

###
POST {{HOST}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "gremlich@duck.com",
    "password": "password"
}

###
DELETE {{HOST}}/api/auth/register/delete?certain=yes&tokenToDelete=someothertoken HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE4MjQzMDUsImV4cCI6MTcxNDI0MzUwNSwiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZSI6WyJ1c2VyIl19.2-6qm1qiLcuBLttVi-uXL8x6PaN_p0tT-g-ASFdRBrvI-8ipjuknEVbacKjLTGX4mKO2v1RnoHneAbh7E_ieOA

###
GET {{HOST}}/api/token/issue?numberToIssue=1&certain=yes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE4MjU5NzQsImV4cCI6MTcxNDI0NTE3NCwiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZXMiOlsidXNlciJdfQ.UBCCzFPDYayS9dnYbr--3pxJDrKJy2ohWuube2kgTESvYbdiudh3GCdivmLz_A__yuAh8gY0s7ujhrO72sOnwA

###
POST {{HOST}}/api/token/verify?certain=yes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTE4MjU5NzQsImV4cCI6MTcxNDI0NTE3NCwiaXNzIjoic2NhbS1ob3VuZC1zZXJ2aWNlIiwicm9sZXMiOlsidXNlciJdfQ.UBCCzFPDYayS9dnYbr--3pxJDrKJy2ohWuube2kgTESvYbdiudh3GCdivmLz_A__yuAh8gY0s7ujhrO72sOnwA

{
    "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzY2FtLWhvdW5kLXNlcnZpY2UiLCJleHAiOjE3MTQyNDUxODQsImlhdCI6MTcxMTgyNTk4NCwidXNlZCI6ZmFsc2UsIml0ZW1JblNldCI6MSwibnVtYmVySW5TZXQiOjEwLCJ2YWx1ZSI6MH0.VlJS-Rgyd6PLBFcQJKKCPYi1E7qV0qLkV6cQ0MMh6Ij1Y5Zi61r5-m9uAwzZU86fJwcBYxP0qOdIzLC9_70d2w",
    "textScamCheck": "Congratulations! We are delighted to inform you that you have emerged as the lucky winner of our prestigious Global Lottery Jackpot. After a rigorous selection process, your email address was chosen as one of the fortunate winners in our random draw."
}
